# Site settings
title: Michael Cranston
email: cranston.michaelrichard@gmail.com
author: Michael Cranston
description: "Thoughts on front-end development."
baseurl: ""
url: "http://mcranston18.github.io"
google_analytics:
animated: false
show_related_posts: false
highlighter: pygments

# Build settings
markdown: kramdown
permalink: /:title/
highlighter: pygments
paginate: 10
gems:
  jekyll-paginate
sass:
  compressed: true
gems: [jekyll-paginate]
