# Site settings
title: Michael Cranston
email: cranston.michaelrichard@gmail.com
author: Michael Cranston
baseurl: ""
url: "http://mcranston18.github.io"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: /:title/
highlighter: rouge
paginate: 40
paginate_path: blog/:num

sass:
  compressed: true
  sass_dir: _sass
plugins: [jekyll-paginate]
